### ISSUE TITLE
Error on Launch - Straight to Error Log Question

### ISSUE THREAD

**Issue by crpngdth2001** [overkillwtf/folon-steamdeck-installer#18]
All steps completed properly in the install guide.

https://pastebin.com/mLJabKE1

Unhandled exception "EXCEPTION_INT_DIVIDE_BY_ZERO" at 0x000141D1777B Fallout4.exe+1D1777B

**Comment by opeyer** [comment]
I'm having the same issue. From what I can gather, the fix is opening up the old Fallout 4 Launcher and changing the settings (it seems changing them to just about anything works?) and then launching the game, but I can't figure out how to do it post-script running. I know that Fallout 4 Launcher in this case is actually something else, but I'm not sure how else to fix this issue. Maybe I can change values in an .ini somewhere?

**Comment by krupar101** [comment]
Great to hear that. If it works then please follow the guidelines in this github issue. 

https://github.com/overkillwtf/folon-steamdeck-installer/issues/9
